import type { Metadata } from "next";
import { Providers } from "./providers";
import { yekan } from "styles/fonts";
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={yekan.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
