import { Navbar } from "@cmp/workspace/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="container mx-auto max-w-5xl">
      <Navbar />
      <main>{children}</main>
    </div>
  );
}
